### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no JSyphon in java.library.path

### ISSUE THREAD

**Issue by clankill3r** [Syphon/Processing#18]
This counts for all RC's and i don't know if it's possible to fix coding wise.
Anyway, if someone get's this error (using eclipse or intelliJ):

`java.lang.UnsatisfiedLinkError: no JSyphon in java.library.path`

Then you have to add something like this in the VM options:

`-java.library.path=/Users/doekewartena/Dropbox/Public/Processing/libraries/Syphon/library`

I just drop this info here so you know.

**Comment by twonb1tc4** [comment]
I'm getting this error in the Processing IDE. Is there any way to fix this without using intellij?

**Comment by Edwardffigueroa** [comment]
I can not use syphon in my intellij, could anyone help me? I have this problem:
`objc[1344]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
java.lang.ClassCastException: processing.awt.PGraphicsJava2D cannot be cast to processing.opengl.PGraphicsOpenGL
	at codeanticode.syphon.SyphonServer.<init>(Unknown Source)
	at Main.setup(Main.java:27)
	at processing.core.PApplet.handleDraw(PApplet.java:2393)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1540)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)
`

**Comment by vade** [comment]
@Edwardffigueroa -java.library.path=/Users/doekewartena/Dropbox/Public/Processing/libraries/Syphon/library

did you actually supply your own path correctly?

**Comment by Edwardffigueroa** [comment]
@vade Yes, I used my address which is: `-Djava.library.path = / Users / edward / Documents / Processing / libraries / Syphon / library /` and I do not understand why it does not work for me :(

**Comment by Edwardffigueroa** [comment]
sorry @vade for spam, did not know where to post and have reply :/

**Comment by codeanticode** [comment]
@clankill3r could you check if this happens with the [final 2.0 release](https://github.com/Syphon/Processing/releases/tag/2.0)?

**Comment by K3TH3R** [comment]
@codeanticode Adding the `-Djava.library.path=` worked, although I'm using a lot of other Processing libraries naturally in Intellij without needing to do this. Also, it seems you need to be very careful about the path when you put it in there, a space between the `-D` and `java.library.path` would fail.

**Comment by valioDOTch** [comment]
This error appears as well when I use the processing IDE.
I'm actually not interested in using another IDE just to circumvent that bug...

**Comment by vitos1k** [comment]
i'm getting this error despite the path to the library is in java.library.path
i've tested using this: println(System.getProperty("java.library.path"));
And sketch even runs and prints the path. and then error occurs and sketch hangs forever
I'm running basic RecieveFrames example

**Comment by vitos1k** [comment]
> 
> 
> i'm getting this error despite the path to the library is in java.library.path
> i've tested using this: println(System.getProperty("java.library.path"));
> And sketch even runs and prints the path. and then error occurs and sketch hangs forever
> I'm running basic RecieveFrames example

I'm using Processing IDE 3.5.4
Latest Syphon3 library from processing Library manager

**Comment by vitos1k** [comment]
Forgot to mention that i'm on windows. With Fresh processing and syphon it still doesn't work :\
`Available Syphon servers:
Syphon 3.0 by Andres Colubri http://andrescolubri.net/
java.lang.UnsatisfiedLinkError: no JSyphon in java.library.path
	at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:408)
	at java.lang.Thread.run(Thread.java:748)
UnsatisfiedLinkError: no JSyphon in java.library.path
A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit application.
`
when printing java.library.path:
C:\Users\username\Documents\Processing\libraries\Syphon\library;

Tried with 32bit and 64bit processing versions. Tried Processing 3.5.3, and on different PC still the same result.

**Comment by bangnoise** [comment]
@vitos1k Syphon is Mac-only
