### ISSUE TITLE
Unable to Install Via Processing 3.0

### ISSUE THREAD

**Issue by Sensebellum** [Syphon/Processing#26]
I am unable to install Syphon for inside of Processing 3.0. Is this bad? Do I need to do it manually?

<img width="873" alt="screen shot 2015-10-08 at 5 58 50 pm" src="https://cloud.githubusercontent.com/assets/7865492/10383621/5d174fd8-6de6-11e5-96f3-60e179632cfa.png">

**Comment by codeanticode** [comment]
This is strange, I can install the latest release of the library, 2.0-RC2, in Processing 3.0.2

**Comment by codeanticode** [comment]
@Sensebellum any updates on this? Are you able to install it on 3.1.1?

**Comment by Sensebellum** [comment]
Hello, yes, I have been able to use it with the new version now thankfully. Thank you for following up and all the solid work!

**Comment by codeanticode** [comment]
Thanks a lot for the update! I will close the issue then.
