### ISSUE TITLE
Custom fragment shader flips image and stops syphon.

### ISSUE THREAD

**Issue by cansik** [Syphon/Processing#29]
I've written a custom fragment shader which is used to draw a shape. Now the syphon library does not send the image over. Only the first frame is sent to the syphon output.

And the image is flipped by 180°.

I send the image with following method:

```java
void sendImageToSyphon()
{
  updatePixels();
  syphon.sendScreen();
}
```

I tried it with various methods, but even with sending the `g` object it doesn't work. I think it is a problem with version 3.0 and higher.

Here is my shape code:

```java
PShader colorShader;
PShape plane;

void init() {
  println("loading shader...");
  colorShader = loadShader("shader/colorMapFrag.glsl");

  // creating plane
  textureMode(NORMAL);
  plane = createShape();
  plane.beginShape();
  plane.noStroke();
  plane.vertex(0, 0, 0);
  plane.vertex(width, 0, 0);
  plane.vertex(width, height, 0);
  plane.vertex(0, height, 0);
  plane.endShape(CLOSE);
};

void render() {
  background(0);

  // set unform types
  colorShader.set("time", (float)(millis() / 1000.0));
  colorShader.set("resolution", (float)width, (float)height);

  shader(colorShader);
  shape(plane);
};
```
Here is an image of the problem. Lefthand is the simple syphon client, righthand the processing window.
![image](https://cloud.githubusercontent.com/assets/5220162/15893244/bfbf3756-2d7e-11e6-850c-af923e031bc3.png)

**Comment by cansik** [comment]
I found the problem: With processing 3, the pixel of the screen won't get updated from the opengl context. You have to do this manually by calling `loadPixels()`.

```java
void sendImageToSyphon()
{
  loadPixels();
  syphon.sendScreen();
}
```

Now it works like a charm:
![image](https://cloud.githubusercontent.com/assets/5220162/15924932/1998797a-2e35-11e6-9229-979d3474debe.png)

**Comment by vade** [comment]
LoadPixels is probably a slow path - likely doing 

OpenGL Draw -> Readback to CPU -> Load Pixels to pImage -> Submit to Syphon (upload back to GPU).

If possible, capture the view port to a texture and submit that to Syphon. Ive lost touch with Processing - so I'm unsure if pImage can be backed as a pure texture, or if there is a pTexture type variable. 

Either way, try to keep things on the GPU for speed :)
