### ISSUE TITLE
Syphon on Calalina

### ISSUE THREAD

**Issue by TomPeak** [Syphon/Processing#37]
… only works properly when the sketch is run as a 32-bit application

**Comment by bangnoise** [comment]
Hi - an update is pending with Processing's internal library manager, in the meantime you can get `Syphon.zip` directly from https://github.com/Syphon/Processing/releases/latest and install to your Processing3/libraries folder.

**Comment by bangnoise** [comment]
Fixed in version 3, now available within Processing.

**Comment by TomPeak** [comment]
Perfect, thx a lot!
