### ISSUE TITLE
getImage() to support pixelDensity(2)

### ISSUE THREAD

**Issue by rpickering** [Syphon/Processing#38]
I'm wondering if some additions to this library would be needed to support higher pixel densities.

In Processing 3 we are able to set `pixelDensity(2);`  (or detect the current display's density using `pixelDensity(displayDensity())`). This results in a sharper GUI on high-resolution displays.

However when using the example `img = client.getImage(img);`, results in this error:

`Trying to copy texture to pixels array of wrong size`

Is there a workaround to this? 

Many thanks

**Comment by vade** [comment]
Im assuming the issue is around here:

https://github.com/Syphon/Processing/blob/master/src/codeanticode/syphon/SyphonClient.java#L289

Is there a call to request the pixel density of an image? Forgive me, I havent toyed with Processing in quite some time. 

Is the expectation now that Processing works in some display 'units' that are invariant to screen density and not 'pixels' ?

Does the Syphon Client `getGraphics` call also have the issue?

**Comment by vade** [comment]
Maybe a better / different question - do individual graphics contexts hold their own pixel densities or is it global to a sketch? 

Ie - does a syphon client in one context need to respect its host pixel density?

Question for how processing handles this:

If an incoming surface from another client app in Syphon native (say, Resolume) is describing just pixels, should it inherit the pixel density of the sketch hosting the client object? Ie: input source is 1920x1080 pixels. Sketch is set to pixel density 2. Should this new surface be a `PImage` whose density is 2, and image width reported as 960x540?



Trying to understand various expectations set by how processing handles this...

**Comment by rpickering** [comment]
I've been trying to understand it too.

This hopefully shines some light on how it works, similar to how CSS deals with pixel density (the width and height measurements don't change. But a 1px measurement now translates to 2px). Note the new pixelWidth/pixelHeight variables in Processing which represent _actual pixels_ and could be used in place of width/height.

```
size(600, 400);
pixelDensity(2);
println(width, height); //600 400
println(pixelWidth, pixelHeight); //1200 800
```

I'm wondering if there's something that is the equivalent of `img.texturePixelWidth();` to feed into JSyphonImage... or maybe I'm barking up the wrong tree.

More discussion here: [https://github.com/processing/processing/issues/3364](https://github.com/processing/processing/issues/3364)

**Comment by rpickering** [comment]
In reply to your question _do individual graphics contexts hold their own pixel densities or is it global to a sketch?_ - the idea in Processing I think is that you set the pixel density **once** in setup() and it becomes global for everything in the sketch. So anything inside that sketch will need to respect that. 

I'm just not quite sure how best to deal with it, possibly just to always use the `pixelWidth` and `pixelHeight` variables as the absolute source of truth, not `width` and `height` which are now a bit slippery as of Processing 3+.

**Comment by vade** [comment]
I think the latter - pixelWidth and pixelHeight makes the most sense to me, as not many tools in 'raster space' make considerations for pixel density outside of the display layer side of things (meaning, your texture is always 2048 pixels and theres no other way to measure it - but  its up to you how you draw that on the output windowing side)

Syphon doesnt really care (and nor do I think it should, right @bangnoise  ?) about display density. If we can keep it pixel units all the way through I think that would be ideal.

**Comment by rpickering** [comment]
Yeah I'd agree, because you can always do `img.resize(width, height)` to half or double it on your canvas if it makes sense to do so.

I'm not really experienced in how libraries in processing work... but maybe simply doing this (in SyphonClient.java) would work as a fix...?

```
int texWidth = img.textureWidth()*pixelDensity;
int texHeight = img.textureHeight()*pixelDensity;
```

**Comment by rpickering** [comment]
I've just confirmed pixelDensity comes back as '1' if it isn't explicitly set.

```
size(600, 400);
println(pixelDensity); //1
```
```
size(600, 400);
pixelDensity(2);
println(pixelDensity); //2
```

**Comment by rpickering** [comment]
After a bit of experimentation with this I've realised the real problem is that PGraphics and PImage work differently (in other words, PImage doesn't care about pixel density, but PGraphics does), and that causes a conflict in the getImage() function as it uses both types.

I've put in a fix that I think is the simplest one under the circumstances and have tested it working, please see pull request!
