### ISSUE TITLE
OSX Big Sur wont allow usage of libJSyphon.jnilib 

### ISSUE THREAD

**Issue by nimitch** [Syphon/Processing#40]
when launching a sketch that includes the release version3 (29 Dec 2019) of syphon/processing on Big Sur
the syphon library fails to load

processing - console log output snippet
not valid for use in process using library validation: library load disallowed by system policy 

in mac/system prefernces/security and privacy I can accept the code from unknown developer 

this time upon starting the sketch an osx alert window states that 
("Syphon" is damaged and can't be opened. You should move it to the bin)  
and only has options of "move to bin" or "cancel" 

<workaround>
recursive removal of extended attributes on the syphon libraries root folder allows the library to run
for example :

sudo xattr -cr ~/Documents/Processing/libraries/Syphon/library/

**Comment by samyk** [comment]
Thanks, the final command (after accepting security privileges) worked for me on macOS Monterey 12.1 on M1 chip

**Comment by codeanticode** [comment]
This should be solve once a signed & notarized release of the library is ready (#42). For the time being, manually setting the library attributes as pointed out by @nimitch is a valid workaround.

**Comment by codeanticode** [comment]
This release is signed and notarized so it should not require setting attribs manually:

https://github.com/Syphon/Processing/releases/tag/latest
